---
- name: Deploy LibSystem Application
  hosts: libsystem_servers
  become: yes

  tasks:
    - name: Copy Docker Compose file
      copy:
        src: ./docker-compose.yml
        dest: ./

    - name: Stop any running containers
      command: docker-compose down

    - name: Start Docker Compose
      command: docker-compose up -d

