
version: '3.9'

networks:
  libSystem:

volumes:
  database-volume:

services:
  database:
    image: mysql:latest
    ports:
     - "3306:3306"
    healthcheck:
      test: ["CMD", "ls"]
    environment:
      MYSQL_ROOT_PASSWORD: Tanvi007*
      MYSQL_DATABASE: LibSystem
      MYSQL_USER: tanvi
      MYSQL_PASSWORD: Tanvi007*
    volumes:
      - database-volume:/var/lib/mysql
    networks:
      - libSystem

  backend:
    build: ./Backend
    environment:
      DB_URL: jdbc:mysql://database:3306/LibSystem?createDatabaseIfNotExist=true
      DB_USERNAME: tanvi
      DB_PASSWORD: Tanvi007*
    networks:
      - libSystem
    ports:
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./Frontend
    networks:
      - libSystem
    ports:
      - "5173:5173"
    depends_on:
      - backend




